import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";

export type InvoicePdfData = {
  invoiceNumber: string;
  title: string;
  projectTitle: string;
  amountCents: number;
  currency: string;
  status: "pending" | "paid";
  issuedAt: string;
  dueDate: string | null;
  businessName: string;
  ownerName: string | null;
  ownerEmail: string;
  clientName: string | null;
  clientEmail: string | null;
  brandPrimary: string | null;
};

function colorFromHex(value: string | null) {
  if (!value || !/^#[0-9a-f]{6}$/i.test(value)) return rgb(0.12, 0.25, 0.58);
  return rgb(
    parseInt(value.slice(1, 3), 16) / 255,
    parseInt(value.slice(3, 5), 16) / 255,
    parseInt(value.slice(5, 7), 16) / 255,
  );
}

function money(cents: number, currency: string) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency.toUpperCase(),
  }).format(cents / 100);
}

function date(value: string | null) {
  if (!value) return "Due on receipt";
  const parsed = new Date(value.includes("T") ? value : `${value}T12:00:00Z`);
  return parsed.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}

function text(
  page: PDFPage,
  value: string,
  x: number,
  y: number,
  font: PDFFont,
  size = 10,
  color = rgb(0.25, 0.27, 0.32),
) {
  page.drawText(value, { x, y, font, size, color });
}

export async function generateInvoicePdf(data: InvoicePdfData) {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Invoice ${data.invoiceNumber}`);
  pdf.setAuthor(data.businessName);
  pdf.setSubject(data.projectTitle);
  pdf.setCreationDate(new Date(data.issuedAt));

  const page = pdf.addPage([612, 792]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const accent = colorFromHex(data.brandPrimary);
  const dark = rgb(0.08, 0.09, 0.12);
  const muted = rgb(0.42, 0.44, 0.49);

  page.drawRectangle({ x: 0, y: 738, width: 612, height: 54, color: accent });
  text(page, data.businessName, 48, 758, bold, 17, rgb(1, 1, 1));

  text(page, "INVOICE", 48, 682, bold, 30, dark);
  text(page, `#${data.invoiceNumber}`, 48, 661, regular, 11, muted);

  const statusLabel = data.status === "paid" ? "PAID" : "PAYMENT DUE";
  const statusColor = data.status === "paid" ? rgb(0.05, 0.55, 0.31) : rgb(0.85, 0.45, 0.05);
  const statusWidth = bold.widthOfTextAtSize(statusLabel, 10) + 24;
  page.drawRectangle({ x: 516 - statusWidth, y: 666, width: statusWidth, height: 24, color: statusColor });
  text(page, statusLabel, 528 - statusWidth, 674, bold, 10, rgb(1, 1, 1));

  text(page, "FROM", 48, 606, bold, 9, muted);
  text(page, data.businessName, 48, 585, bold, 12, dark);
  if (data.ownerName) text(page, data.ownerName, 48, 568, regular, 10, muted);
  text(page, data.ownerEmail, 48, data.ownerName ? 551 : 568, regular, 10, muted);

  text(page, "BILL TO", 330, 606, bold, 9, muted);
  text(page, data.clientName || data.clientEmail || "Client", 330, 585, bold, 12, dark);
  if (data.clientName && data.clientEmail) text(page, data.clientEmail, 330, 568, regular, 10, muted);

  page.drawLine({ start: { x: 48, y: 520 }, end: { x: 564, y: 520 }, thickness: 1, color: rgb(0.88, 0.89, 0.91) });
  text(page, "ISSUED", 48, 494, bold, 9, muted);
  text(page, date(data.issuedAt), 48, 474, regular, 11, dark);
  text(page, "DUE", 250, 494, bold, 9, muted);
  text(page, date(data.dueDate), 250, 474, regular, 11, dark);
  text(page, "PROJECT", 420, 494, bold, 9, muted);
  text(page, data.projectTitle.slice(0, 25), 420, 474, regular, 11, dark);

  page.drawRectangle({ x: 48, y: 405, width: 516, height: 38, color: rgb(0.96, 0.97, 0.98) });
  text(page, "DESCRIPTION", 62, 419, bold, 9, muted);
  text(page, "AMOUNT", 488, 419, bold, 9, muted);
  text(page, data.title || `Services for ${data.projectTitle}`, 62, 377, regular, 11, dark);
  const total = money(data.amountCents, data.currency);
  text(page, total, 552 - regular.widthOfTextAtSize(total, 11), 377, regular, 11, dark);
  page.drawLine({ start: { x: 48, y: 354 }, end: { x: 564, y: 354 }, thickness: 1, color: rgb(0.88, 0.89, 0.91) });

  text(page, data.status === "paid" ? "TOTAL PAID" : "TOTAL DUE", 378, 310, bold, 10, muted);
  text(page, total, 552 - bold.widthOfTextAtSize(total, 22), 278, bold, 22, dark);

  text(page, "Payment", 48, 190, bold, 11, dark);
  text(
    page,
    data.status === "paid"
      ? "This invoice has been recorded as paid."
      : "Pay securely from your Finalia workspace using Stripe Checkout.",
    48,
    170,
    regular,
    10,
    muted,
  );
  text(page, "Generated by Finalia", 48, 52, regular, 9, muted);
  text(page, `Invoice ${data.invoiceNumber}`, 466, 52, regular, 9, muted);

  return pdf.save();
}
